# Testes das requisições com a extensão REST CLIENT do vscode

@HOST = http://localhost:3000

# HEALTH CHECK
GET {{HOST}}/health

###

GET {{HOST}}/user

###

POST  {{HOST}}/user
Content-Type: application/json

{
    "nome": "test",
    "email": "test@test.com",
    "senha": "123"
}

###

GET {{HOST}}/user?id=1
